# Generated by Django 2.1.2 on 2018-11-01 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_Company', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.UUID('589c7836-4834-4302-a033-3bbd9b858790'), editable=False, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('datafile', models.FileField(upload_to='')),
                ('id', models.UUIDField(default=uuid.UUID('dc3a98fc-5fe0-4640-bd49-78526178b517'), editable=False, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileFeedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('289f1779-812d-405f-84c7-bb358a60f3e1'), editable=False, primary_key=True, serialize=False)),
                ('status_text', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileScholarshipItem',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=255)),
                ('id', models.UUIDField(default=uuid.UUID('d14927e4-4586-4415-89d7-3fe50efce08f'), editable=False, primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('tag1', models.CharField(max_length=255)),
                ('tag2', models.CharField(max_length=255)),
                ('tag3', models.CharField(max_length=255)),
                ('tag4', models.CharField(blank=True, max_length=255)),
                ('tag5', models.CharField(blank=True, max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
