# Generated by Django 2.1.2 on 2018-11-01 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_api', '0002_auto_20181101_0323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_Company',
            new_name='is_company',
        ),
    ]
